#!perl

use strict;
use warnings;
use utf8;

use App::Croon::Cron;

use Test::More;

subtest 'normal (like a raw cron)' => sub {
    my $cron = App::Croon::Cron::translate_from_obj({
        name    => 'normal',
        min     => 1,
        hour    => 1,
        day     => 1,
        month   => 1,
        w_day   => 1,
        command => 'touch ~/right_$(date +%Y%m%d).txt',
    });

    is $cron, <<'EOC';
# normal: this cron was generated by Croon {{{
1 1 1 1 1 touch ~/right_$(date +\%Y\%m\%d).txt
# }}} normal
EOC
};

subtest 'weekday' => sub {
    my $cron;

    $cron = App::Croon::Cron::translate_from_obj({
        name    => 'weekday',
        min     => 1,
        hour    => 1,
        day     => 1,
        month   => 1,
        w_day   => 'Mon',
        command => 'echo "hello"',
    });
    is $cron, <<'EOC', 'Specify weekday as string';
# weekday: this cron was generated by Croon {{{
1 1 1 1 1 echo "hello"
# }}} weekday
EOC

    $cron = App::Croon::Cron::translate_from_obj({
        name    => 'weekday',
        min     => 1,
        hour    => 1,
        day     => 1,
        month   => 1,
        command => 'echo "hello"',
    });
    is $cron, <<'EOC', 'Not specified weekday';
# weekday: this cron was generated by Croon {{{
1 1 1 1 * echo "hello"
# }}} weekday
EOC
};

subtest 'min' => sub {
    my $cron;

    $cron = App::Croon::Cron::translate_from_obj({
        name    => 'min',
        hour    => 1,
        day     => 1,
        month   => 1,
        w_day   => 1,
        command => 'echo "hello"',
    });
    is $cron, <<'EOC', 'Not specified min';
# min: this cron was generated by Croon {{{
* 1 1 1 1 echo "hello"
# }}} min
EOC
};

subtest 'hour' => sub {
    my $cron;

    $cron = App::Croon::Cron::translate_from_obj({
        name    => 'hour',
        min     => 1,
        day     => 1,
        month   => 1,
        w_day   => 1,
        command => 'echo "hello"',
    });
    is $cron, <<'EOC', 'Not specified hour';
# hour: this cron was generated by Croon {{{
1 * 1 1 1 echo "hello"
# }}} hour
EOC
};

subtest 'day' => sub {
    my $cron;

    $cron = App::Croon::Cron::translate_from_obj({
        name    => 'day',
        min     => 1,
        hour    => 1,
        month   => 1,
        w_day   => 1,
        command => 'echo "hello"',
    });
    is $cron, <<'EOC', 'Not specified day';
# day: this cron was generated by Croon {{{
1 1 * 1 1 echo "hello"
# }}} day
EOC
};

subtest 'month' => sub {
    my $cron;

    $cron = App::Croon::Cron::translate_from_obj({
        name    => 'month',
        min     => 1,
        hour    => 1,
        day     => 1,
        month   => 'Jan',
        w_day   => 1,
        command => 'echo "hello"',
    });
    is $cron, <<'EOC', 'Specify month as string';
# month: this cron was generated by Croon {{{
1 1 1 1 1 echo "hello"
# }}} month
EOC

    $cron = App::Croon::Cron::translate_from_obj({
        name    => 'month',
        min     => 1,
        hour    => 1,
        day     => 1,
        w_day   => 1,
        command => 'echo "hello"',
    });
    is $cron, <<'EOC', 'Not specified month';
# month: this cron was generated by Croon {{{
1 1 1 * 1 echo "hello"
# }}} month
EOC
};

subtest 'Sepcify `min` and `hour` as time format' => sub {
    my $cron = App::Croon::Cron::translate_from_obj({
        name    => 'egashira',
        time    => '02:50',
        min     => 1, # <= should be ignored
        hour    => 1, # <= should be ignored
        day     => 1,
        month   => 1,
        w_day   => 1,
        command => 'touch ~/right_$(date +%Y%m%d).txt',
    });

    is $cron, <<'EOC';
# egashira: this cron was generated by Croon {{{
50 2 1 1 1 touch ~/right_$(date +\%Y\%m\%d).txt
# }}} egashira
EOC
};

subtest 'tick' => sub {
    my $cron = App::Croon::Cron::translate_from_obj({
        name    => 'tick',
        min     => 'every 2',
        hour    => 'every 3',
        day     => 'every 4',
        month   => 'every 5',
        w_day   => 'every 6',
        command => 'touch ~/right_$(date +%Y%m%d).txt',
    });

    is $cron, <<'EOC';
# tick: this cron was generated by Croon {{{
*/2 */3 */4 */5 */6 touch ~/right_$(date +\%Y\%m\%d).txt
# }}} tick
EOC
};

subtest 'exceptional' => sub {
    eval {
        my $cron = App::Croon::Cron::translate_from_obj({
            name    => '',
            min     => 1,
            hour    => 1,
            day     => 1,
            month   => 1,
            w_day   => 1,
            command => 'touch ~/right_$(date +%Y%m%d).txt',
        });
    };
    ok $@, 'Name is required';

    eval {
        my $cron = App::Croon::Cron::translate_from_obj({
            name    => 'name',
            min     => 1,
            hour    => 1,
            day     => 1,
            month   => 1,
            w_day   => 1,
            command => '',
        });
    };
    ok $@, 'Command is required';
};

done_testing;
