#!perl

use strict;
use warnings;
use utf8;

use App::Croon::Cron;

use Test::More;

subtest 'normal (like a raw cron)' => sub {
    my $cron = App::Croon::Cron::translate_from_obj({
        name    => 'normal',
        min     => 1,
        hour    => 1,
        day     => 1,
        month   => 1,
        w_day   => 1,
        command => 'touch ~/right_$(date +%Y%m%d).txt',
    });

    is $cron, <<'EOC';
# normal: this cron was generated by Croon {{{
1 1 1 1 1 touch ~/right_$(date +\%Y\%m\%d).txt
# }}} normal
EOC
};

subtest 'weekday' => sub {
    my $cron;

    $cron = App::Croon::Cron::translate_from_obj({
        name    => 'weekday',
        min     => 1,
        hour    => 1,
        day     => 1,
        month   => 1,
        w_day   => 'Mon',
        command => 'echo "hello"',
    });
    is $cron, <<'EOC', 'Specify weekday as string';
# weekday: this cron was generated by Croon {{{
1 1 1 1 1 echo "hello"
# }}} weekday
EOC

    eval {
        $cron = App::Croon::Cron::translate_from_obj({
            name    => 'weekday',
            min     => 1,
            hour    => 1,
            day     => 1,
            month   => 1,
            command => 'echo "hello"',
        });
    };
    is $cron, <<'EOC', 'Not specified weekday';
# weekday: this cron was generated by Croon {{{
1 1 1 1 * echo "hello"
# }}} weekday
EOC

    eval {
        $cron = App::Croon::Cron::translate_from_obj({
            name    => 'weekday',
            min     => 1,
            hour    => 1,
            day     => 1,
            month   => 1,
            w_day   => 7,
            command => 'echo "hello"',
        });
    };
    ok $@, 'Invalid weekday is specified as number';

    eval {
        $cron = App::Croon::Cron::translate_from_obj({
            name    => 'weekday',
            min     => 1,
            hour    => 1,
            day     => 1,
            month   => 1,
            w_day   => 'Invalid',
            command => 'echo "hello"',
        });
    };
    ok $@, 'Invalid weekday is specified as string';
};

subtest 'min' => sub {
    my $cron;

    eval {
        $cron = App::Croon::Cron::translate_from_obj({
            name    => 'min',
            min     => 60,
            hour    => 1,
            day     => 1,
            month   => 1,
            w_day   => 1,
            command => 'echo "hello"',
        });
    };
    ok $@, 'Over 60 min';

    eval {
        $cron = App::Croon::Cron::translate_from_obj({
            name    => 'min',
            hour    => 1,
            day     => 1,
            month   => 1,
            w_day   => 1,
            command => 'echo "hello"',
        });
    };
    is $cron, <<'EOC', 'Not specified min';
# min: this cron was generated by Croon {{{
* 1 1 1 1 echo "hello"
# }}} min
EOC
};

subtest 'hour' => sub {
    my $cron;

    eval {
        $cron = App::Croon::Cron::translate_from_obj({
            name    => 'hour',
            min     => 1,
            hour    => 24,
            day     => 1,
            month   => 1,
            w_day   => 1,
            command => 'echo "hello"',
        });
    };
    ok $@, 'Over 24 hours';

    eval {
        $cron = App::Croon::Cron::translate_from_obj({
            name    => 'hour',
            min     => 1,
            day     => 1,
            month   => 1,
            w_day   => 1,
            command => 'echo "hello"',
        });
    };
    is $cron, <<'EOC', 'Not specified hour';
# hour: this cron was generated by Croon {{{
1 * 1 1 1 echo "hello"
# }}} hour
EOC
};

subtest 'day' => sub {
    my $cron;

    eval {
        $cron = App::Croon::Cron::translate_from_obj({
            name    => 'day',
            min     => 1,
            hour    => 1,
            day     => 32,
            month   => 1,
            w_day   => 1,
            command => 'echo "hello"',
        });
    };
    ok $@, 'Over 32 days';

    eval {
        $cron = App::Croon::Cron::translate_from_obj({
            name    => 'day',
            min     => 1,
            hour    => 1,
            month   => 1,
            w_day   => 1,
            command => 'echo "hello"',
        });
    };

    is $cron, <<'EOC', 'Not specified day';
# day: this cron was generated by Croon {{{
1 1 * 1 1 echo "hello"
# }}} day
EOC
};

subtest 'month' => sub {
    my $cron;

    $cron = App::Croon::Cron::translate_from_obj({
        name    => 'month',
        min     => 1,
        hour    => 1,
        day     => 1,
        month   => 'Jan',
        w_day   => 1,
        command => 'echo "hello"',
    });
    is $cron, <<'EOC', 'Specify month as string';
# month: this cron was generated by Croon {{{
1 1 1 1 1 echo "hello"
# }}} month
EOC

    $cron = App::Croon::Cron::translate_from_obj({
        name    => 'month',
        min     => 1,
        hour    => 1,
        month   => 1,
        w_day   => 1,
        command => 'echo "hello"',
    });
    is $cron, <<'EOC', 'Not specified day';
# month: this cron was generated by Croon {{{
1 1 * 1 1 echo "hello"
# }}} month
EOC

    eval {
        $cron = App::Croon::Cron::translate_from_obj({
            name    => 'month',
            min     => 1,
            hour    => 1,
            day     => 1,
            month   => 13,
            w_day   => 1,
            command => 'echo "hello"',
        });
    };
    ok $@, 'Over 13 months';
};

done_testing;
