#!perl

use strict;
use warnings;
use utf8;

use App::Croon::Cron;

use Test::More;

subtest 'exclusion by time range' => sub {
    my $cron = App::Croon::Cron::translate_from_obj({
        name      => 'exclusion',
        min       => 1,
        hour      => 1,
        day       => 1,
        month     => 1,
        w_day     => 1,
        command   => 'touch ~/right_$(date +%Y%m%d).txt',
        exclusion => {
            from => '08:00:00',
            to   => '08:59:59',
        }
    });

    is $cron, <<'EOC';
# exclusion: this cron was generated by Croon {{{
1 1 1 1 1 now=`date +"%H%M%S"` && if ([ 080000 -le $now ] && [ $now -le 085959 ]) ; then touch ~/right_$(date +\%Y\%m\%d).txt ; fi
# }}} exclusion
EOC
};

subtest 'exceptional' => sub {
    eval {
        App::Croon::Cron::translate_from_obj({
            name      => 'exclusion',
            min       => 1,
            hour      => 1,
            day       => 1,
            month     => 1,
            w_day     => 1,
            command   => 'touch ~/right_$(date +%Y%m%d).txt',
            exclusion => {},
        });
    };
    ok $@;
};

done_testing;
