#!perl

use strict;
use warnings;
use utf8;

use App::Croon::Cron;

use Test::More;

subtest 'stderr and stdout' => sub {
    subtest 'both are the same' => sub {
        my $cron = App::Croon::Cron::translate_from_obj({
            name       => 'the same',
            min        => 1,
            hour       => 1,
            day        => 1,
            month      => 1,
            w_day      => 1,
            command    => 'touch ~/right_$(date +%Y%m%d).txt',
            stdout_log => '/tmp/log',
            stderr_log => '/tmp/log',
        });

        is $cron, <<'EOC';
# the same: this cron was generated by Croon {{{
1 1 1 1 1 touch ~/right_$(date +\%Y\%m\%d).txt >/tmp/log 2>&1
# }}} the same
EOC
    };

    subtest 'different destination' => sub {
        my $cron = App::Croon::Cron::translate_from_obj({
            name       => 'different dest',
            min        => 1,
            hour       => 1,
            day        => 1,
            month      => 1,
            w_day      => 1,
            command    => 'touch ~/right_$(date +%Y%m%d).txt',
            stdout_log => '/tmp/log/stdout',
            stderr_log => '/tmp/log/stderr',
        });

        is $cron, <<'EOC';
# different dest: this cron was generated by Croon {{{
1 1 1 1 1 touch ~/right_$(date +\%Y\%m\%d).txt 1>/tmp/log/stdout 2>/tmp/log/stderr
# }}} different dest
EOC
    };
};

subtest 'stdout only' => sub {
    my $cron = App::Croon::Cron::translate_from_obj({
        name       => 'stdout only',
        min        => 1,
        hour       => 1,
        day        => 1,
        month      => 1,
        w_day      => 1,
        command    => 'touch ~/right_$(date +%Y%m%d).txt',
        stdout_log => '/tmp/log/stdout',
    });

    is $cron, <<'EOC';
# stdout only: this cron was generated by Croon {{{
1 1 1 1 1 touch ~/right_$(date +\%Y\%m\%d).txt 1>/tmp/log/stdout
# }}} stdout only
EOC
};

subtest 'stderr only' => sub {
    my $cron = App::Croon::Cron::translate_from_obj({
        name       => 'stderr only',
        min        => 1,
        hour       => 1,
        day        => 1,
        month      => 1,
        w_day      => 1,
        command    => 'touch ~/right_$(date +%Y%m%d).txt',
        stderr_log => '/tmp/log/stderr',
    });

    is $cron, <<'EOC';
# stderr only: this cron was generated by Croon {{{
1 1 1 1 1 touch ~/right_$(date +\%Y\%m\%d).txt 2>/tmp/log/stderr
# }}} stderr only
EOC
};
done_testing;
